### ISSUE TITLE
Tsk tsk tsk

### ISSUE THREAD

**Issue by Baddaboo** [tsaoman/cuttlefish-cmdb#1]
You should include a license with your projects you upload to Github
...
...
...
Also migrating to Python 3 is more of a downgrade than an upgrade tbh

**Comment by tsaoman** [comment]
Added license / copyright disclaimer. License will be added when I've determined the future of the project more fully, most likely within the next 2 weeks.

**Comment by tsaoman** [comment]
Licensed under AGPLv3.
